display
handleError: anException
	self informAnExceptionFor: anException.
	anException resume