display
handleFailure: anException
	self informAnExceptionFor: anException.
	anException return